version: "0.4.0.{build}"
image: Visual Studio 2017

before_build: 
  - ps: "dotnet restore"
build: 
  verbosity: minimal
test_script: 
  ps: "dotnet test .\\test\\CommandQuery.Specs\\CommandQuery.Specs.csproj"
